const URL_BASE = import.meta.env.VITE_REACT_APP_BASE_URL;
export const END_POINTS ={
    LOGIN: `${URL_BASE}User`,
    UPDATE_PASSWORD: `${URL_BASE}UsuariosLoginSys/update-password`,

    GET_ORGANIZATIONS: `${URL_BASE}Common/Organizaciones`,
    UPDATE_CAJAS: `${URL_BASE}Contab/UpdateCaja`,
    REPORTE_GESTIONES_COBROS: `${URL_BASE}GestionCobros/Parametros`,
    REPORTE_GESTIONES_CLOUD: `${URL_BASE}GestionPureCloud/Parametros`,
    REPORTE_VENTAS: `${URL_BASE}ReporteVenta`,
    REPORTES_MATRICULACION_SRI: `${URL_BASE}Matricula/Parametros`,
    REPORTES_COMPORTAMIENTO_PAGOS: `${URL_BASE}GestionPureCloud/comportamiento-pagos`,
    REPORTES_USUARIOS_ORACLE: `${URL_BASE}ReporteUsuarios/usuarios-oracle`,
    REPORTES_MATRICULACION_EXCEL: `${URL_BASE}Matricula/Excel/Parametros`,
    REPORTES_MATRICULACION_PROCESO_VALORES: `${URL_BASE}Matricula/Parametros/ProcesaValores`,
    REPORTES_MATRICULACION_REPORTE: `${URL_BASE}Matricula/Parametros/Reporte`,
    REPORTES_MATRICULACION_CC: `${URL_BASE}Matricula/CC/Parametros`,
    REPORTES_MATRICULACION_VISOR: `${URL_BASE}Matricula/Visor/Parametros`,
    REPORTES_GESTIONES_COBROS_JSON: `${URL_BASE}GestionCobros/Busqueda`,
    REPORTES_CUOTA_CERO_NO_PAGADO: `${URL_BASE}Cartera/Parametros`,
    GET_REVISION_MOTO_AURA: `${URL_BASE}Aura/GET-INFO-FACTURA`,
    GET_INFORMACION_GARANTIA_MOTO: `${URL_BASE}Aura/GET-INFO-GARANTIA-MOTO`,
    UPDATE_CELULAR_AURA: `${URL_BASE}Aura/UPDATE-TELEFONO`,
    UPDATE_EMAIL_AURA: `${URL_BASE}Aura/UPDATE-EMAIL`,
    CREATE_GARANTIA: `${URL_BASE}Aura/CREATE-NEW-ACTIVATION-GARANTIA`,
    GET_GARANTIA: `${URL_BASE}Aura/VERIFICAR-REGISTRO-GARANTIA`,
    UPDATE_CALIFICACION: `${URL_BASE}Aura/UPDATE-CALIFICACION-ENCUESTA`,
    SEARCH_CLIENT: `${URL_BASE}ClientesOpen/info-cliente-open-bravo`,
    OBTENER_VALORES_MATRICULA: `${URL_BASE}AnticipoMatricula/obtener-valores-matricula`,
    DESCARGAR_DOCUMENTO_ANTICIPO: `${URL_BASE}DocAnticiposPdfs/descargar-pdf-anticipo`,
    DESCARGAR_DOCUMENTO_LIQUIDACION: `${URL_BASE}DocAnticiposPdfs/descargar-pdf-liquidacion`,
    SEARCH_ANTICIPO_PATRICULA: `${URL_BASE}AnticipoMatricula/search-anticipo`,
    GRABAR_LIQUIDACION: `${URL_BASE}Liquidacion/grabar-liquidacion`,
    GRABAR_IMAGENES_LIQUIDACION: `${URL_BASE}Documentos/cargar-liquidacion-imagenes`,
    DESCARGAR_REPORTE_VERIFICACIONES: `${URL_BASE}Verificaciones/reporte-verificacion`,
    SEARCH_ORDEN_TRABAJO: `${URL_BASE}EncuestaPostVenta/search-orden-trabajo`,
    RECORD_ENCUESTA: `${URL_BASE}EncuestaPostVenta/record-encuesta`,
    REPORTE_ACTIVACION_GARANTIA: `${URL_BASE}ReportesPostVenta/reporte-activacion-garantia`,
    REPORTE_POST_VENTA: `${URL_BASE}ReportesPostVenta/reporte-postventa`, 
    REPORTE_CARTERA_SALDOS: `${URL_BASE}Cartera/Saldos`, 
    REPORTE_LIQUIDACIONES: `${URL_BASE}Liquidacion/reporte-liquidaciones`, 
    REPORTE_ANTICIPOS: `${URL_BASE}AnticipoMatricula/reporte-anticipo`, 
    OBTENER_DEVOLUCIONS_x_APROBAR: `${URL_BASE}Devoluciones/obtener-anticipo-X-Anular`,
    OBTENER_AGENCIAS_USUARIOS: `${URL_BASE}AuditoriaInventario/obtener-agencias-x-usuarios`,
    OBTENER_AGENCIAS_USUARIOS_FINALIZAR: `${URL_BASE}AuditoriaInventario/obtener-agencias-x-usuarios-finalizado`,
    OBTENER_AGENCIAS_USUARIOS_REPORTE: `${URL_BASE}AuditoriaInventario/obtener-agencias-x-usuarios-reporte`,
    BUSCAR_PRODUCTO_AUDITORIA: `${URL_BASE}AuditoriaInventario/buscar-productos-x-id`, 
    FINALIZAR_AUDITORIA_AGENCIA: `${URL_BASE}AuditoriaInventario/finalizar-auditoria`, 
    GRABAR_PRODUCTO_AUDITORIA: `${URL_BASE}AuditoriaInventario/grabar-auditoria-item`, 
    REPORTE_AUDITORIA_X_AGENCIA: `${URL_BASE}AuditoriaInventario/reporte-reconteo`, 
    REPORTE_AUDITORIA_X_AGENCIA_STOCK: `${URL_BASE}AuditoriaInventario/reporte-item-no-contados`, 
    REPORTE_AUDITORIA_PDF_ITEMS_OPEN: `${URL_BASE}AuditoriaInventario/descargar-reporte-stock-open`, 
    REPORTE_AUDITORIA_PDF: `${URL_BASE}AuditoriaInventario/descargar-reporte-pdf`,   
    REPORTE_AUDITORIA_EXCEL: `${URL_BASE}AuditoriaInventario/descargar-reporte-excel`,
    DESCARGAR_ACTA_AUDITORIA: `${URL_BASE}AuditoriaInventario/descargar-acta-auditoria`, 
    OBTENER_ANTICIPOS_PARA_DEVOLUCION: `${URL_BASE}Devoluciones/obtener-anticipos`,  
    GRABAR_ANTICPO_DEVOLUCION: `${URL_BASE}Devoluciones/create-devolucion-anticipo`,   
    UPDATE_ANTICPO_DEVOLUCION: `${URL_BASE}Devoluciones/update-status-anticipacion-anulacion`, 
    DOWNLOAD_ACTA_DEVOLUCION: `${URL_BASE}Devoluciones/descargar-devolucion-anticipo`,   
    UPLOAD_LIST_PRICE_EXCEL: `${URL_BASE}PriceListProduct/upload-excel-list-price`,  
    SEARCH_ITEM_PRICE: `${URL_BASE}PriceListProduct/search-item-price`,   
    // DESCARGAR_DOCUMENTO_ANTICIPO: `${URL_BASE}DocAnticiposPdfs/descargar-pdf-anticipo`,  
    // DESCARGAR_DOCUMENTO_ANTICIPO: `${URL_BASE}DocAnticiposPdfs/descargar-pdf-anticipo`, 
    // DESCARGAR_DOCUMENTO_LIQUIDACION: `${URL_BASE}DocAnticiposPdfs/descargar-pdf-liquidacion`, 
    GRABAR_ANTICIPO_MATRICULA: `https://servicios.unnoparts.com.ec/api/AnticipoAura`,
    DESCARGAR_DOCUMENTO_ACTA_ENTREGA_VEHICULO: `${URL_BASE}DocActaRecepMatri/descargar-acta-recepcion-vehiculo`,  
}